#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Plan, install, verify, and uninstall PPC Lab LTS server deployment assets."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import stat
import sys
from pathlib import Path, PurePosixPath
from typing import Any

DEPLOYMENT_SCHEMA = "ppc-lab-deployment-v1"
REPORT_SCHEMA = "ppc-lab-deployment-report-v1"
API_VERSION = 1

class DeployError(RuntimeError):
    pass

def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()

def project_version(root: Path) -> str:
    text=(root/'CMakeLists.txt').read_text(encoding='utf-8')
    m=re.search(r'project\(PPCLab VERSION ([0-9]+\.[0-9]+\.[0-9]+)',text)
    if not m: raise DeployError('cannot determine PPC Lab version')
    return m.group(1)

def absolute(value: str, field: str) -> str:
    p=PurePosixPath(value)
    if not p.is_absolute() or '..' in p.parts:
        raise DeployError(f'{field} must be an absolute normalized POSIX path')
    return p.as_posix()

def staged(dest_root: Path, absolute_path: str) -> Path:
    rel=PurePosixPath(absolute_path).relative_to('/')
    return dest_root.joinpath(*rel.parts)

def unit_api(prefix:str, config_root:str, state_root:str, target_root:str, run_user:str)->str:
    return f'''[Unit]\nDescription=PPC Lab Research API\nAfter=network.target\n\n[Service]\nType=simple\nUser={run_user}\nGroup={run_user}\nEnvironmentFile={config_root}/ppc-lab.env\nExecStart={prefix}/bin/ppc-lab-api --host ${{PPC_LAB_API_HOST}} --port ${{PPC_LAB_API_PORT}} --ppc-lab {prefix}/bin/ppc-lab --worker {prefix}/bin/ppc-lab-worker --evidence {prefix}/bin/ppc-lab-evidence --root {target_root} --evidence-store {state_root}/evidence --job-timeout ${{PPC_LAB_JOB_TIMEOUT}} --max-body ${{PPC_LAB_MAX_BODY}}\nRestart=on-failure\nRestartSec=2\nNoNewPrivileges=true\nPrivateTmp=true\nProtectSystem=strict\nProtectHome=read-only\nProtectKernelTunables=true\nProtectKernelModules=true\nProtectControlGroups=true\nRestrictSUIDSGID=true\nReadOnlyPaths={target_root}\nReadWritePaths={state_root}\n\n[Install]\nWantedBy=multi-user.target\n'''

def unit_control(prefix:str, config_root:str, state_root:str, run_user:str)->str:
    return f'''[Unit]\nDescription=PPC Lab Campaign Control Plane\nAfter=network.target\n\n[Service]\nType=simple\nUser={run_user}\nGroup={run_user}\nEnvironmentFile={config_root}/ppc-lab.env\nExecStart={prefix}/bin/ppc-lab-control serve {state_root}/control --scheduler-tool {prefix}/bin/ppc-lab-schedule --max-active ${{PPC_LAB_CONTROL_MAX_ACTIVE}} --poll-seconds ${{PPC_LAB_CONTROL_POLL_SECONDS}}\nRestart=on-failure\nRestartSec=2\nNoNewPrivileges=true\nPrivateTmp=true\nProtectSystem=strict\nProtectHome=read-only\nProtectKernelTunables=true\nProtectKernelModules=true\nProtectControlGroups=true\nRestrictSUIDSGID=true\nReadWritePaths={state_root}\n\n[Install]\nWantedBy=multi-user.target\n'''

def build_plan(ns:argparse.Namespace)->dict[str,Any]:
    root=ns.root.resolve()
    prefix=absolute(ns.prefix,'prefix'); state_root=absolute(ns.state_root,'state-root')
    config_root=absolute(ns.config_root,'config-root'); cache_root=absolute(ns.cache_root,'cache-root')
    log_root=absolute(ns.log_root,'log-root'); target_root=absolute(ns.target_root,'target-root')
    services=['api','control'] if ns.service=='both' else [ns.service]
    env=(
        '# Generated by ppc-lab-deploy. Keep mode 0600 if PPC_LAB_API_TOKEN is set.\n'
        f'PPC_LAB_API_HOST={ns.api_host}\nPPC_LAB_API_PORT={ns.api_port}\n'
        f'PPC_LAB_JOB_TIMEOUT={ns.job_timeout}\nPPC_LAB_MAX_BODY={ns.max_body}\n'
        f'PPC_LAB_CONTROL_MAX_ACTIVE={ns.control_max_active}\nPPC_LAB_CONTROL_POLL_SECONDS={ns.control_poll_seconds}\n'
        'PPC_LAB_API_TOKEN=\n'
    ).encode()
    files=[]
    def add(path:str,data:bytes,mode:int,kind:str)->None:
        files.append({'path':path,'mode':f'{mode:04o}','kind':kind,'sha256':sha256_bytes(data),'content':data.decode('utf-8')})
    add(f'{config_root}/ppc-lab.env',env,0o600,'environment')
    if 'api' in services: add('/etc/systemd/system/ppc-lab-api.service',unit_api(prefix,config_root,state_root,target_root,ns.run_user).encode(),0o644,'systemd-unit')
    if 'control' in services: add('/etc/systemd/system/ppc-lab-control.service',unit_control(prefix,config_root,state_root,ns.run_user).encode(),0o644,'systemd-unit')
    directories=[
        {'path':state_root,'mode':'0750','kind':'state'},
        {'path':f'{state_root}/control','mode':'0750','kind':'state'},
        {'path':f'{state_root}/evidence','mode':'0750','kind':'state'},
        {'path':f'{state_root}/knowledge','mode':'0750','kind':'state'},
        {'path':cache_root,'mode':'0750','kind':'cache'},
        {'path':log_root,'mode':'0750','kind':'log'},
        {'path':target_root,'mode':'0750','kind':'target-input-root'},
        {'path':config_root,'mode':'0750','kind':'config'},
    ]
    manifest_path=f'{config_root}/deployment.json'
    return {
        'schema':DEPLOYMENT_SCHEMA,'deployment_api':API_VERSION,'ppc_lab_version':project_version(root),
        'platform':'linux-systemd','service':ns.service,'run_user':ns.run_user,
        'prefix':prefix,'state_root':state_root,'config_root':config_root,'cache_root':cache_root,'log_root':log_root,'target_root':target_root,
        'files':files,'directories':directories,'manifest_path':manifest_path,
        'activation':{'daemon_reload':'systemctl daemon-reload','enable_now':[f'systemctl enable --now ppc-lab-{s}.service' for s in services]},
        'policy':{'target_binaries_copied':False,'uninstall_preserves_state':True,'remote_api_requires_token':True},
    }

def public_plan(plan:dict[str,Any])->dict[str,Any]:
    out=dict(plan); out['files']=[{k:v for k,v in f.items() if k!='content'} for f in plan['files']]; return out

def write_json(path:Path,doc:dict[str,Any],mode:int=0o600)->None:
    path.parent.mkdir(parents=True,exist_ok=True)
    tmp=path.with_name(path.name+f'.tmp-{os.getpid()}')
    tmp.write_text(json.dumps(doc,indent=2,sort_keys=True)+'\n',encoding='utf-8'); os.chmod(tmp,mode); os.replace(tmp,path)

def install(plan:dict[str,Any],dest_root:Path)->dict[str,Any]:
    dest_root=dest_root.resolve(); created=[]
    for d in plan['directories']:
        p=staged(dest_root,d['path']); p.mkdir(parents=True,exist_ok=True); os.chmod(p,int(d['mode'],8)); created.append(d['path'])
    for item in plan['files']:
        p=staged(dest_root,item['path']); p.parent.mkdir(parents=True,exist_ok=True); p.write_text(item['content'],encoding='utf-8'); os.chmod(p,int(item['mode'],8)); created.append(item['path'])
    manifest=public_plan(plan)
    mp=staged(dest_root,plan['manifest_path']); write_json(mp,manifest,0o600); created.append(plan['manifest_path'])
    return {'schema':REPORT_SCHEMA,'operation':'install','ok':True,'deployment':manifest,'dest_root':str(dest_root),'created':created}

def load_manifest(path:Path)->dict[str,Any]:
    doc=json.loads(path.read_text(encoding='utf-8'))
    if doc.get('schema')!=DEPLOYMENT_SCHEMA: raise DeployError(f'unsupported deployment manifest schema: {doc.get("schema")}')
    return doc

def verify(manifest:dict[str,Any],dest_root:Path)->dict[str,Any]:
    errors=[]; checked=[]; dest_root=dest_root.resolve()
    for d in manifest.get('directories',[]):
        p=staged(dest_root,d['path']); checked.append(d['path'])
        if not p.is_dir(): errors.append(f'missing directory: {d["path"]}')
        elif p.is_symlink(): errors.append(f'directory must not be a symlink: {d["path"]}')
    for item in manifest.get('files',[]):
        p=staged(dest_root,item['path']); checked.append(item['path'])
        if not p.is_file(): errors.append(f'missing file: {item["path"]}'); continue
        if p.is_symlink(): errors.append(f'file must not be a symlink: {item["path"]}'); continue
        digest=hashlib.sha256(p.read_bytes()).hexdigest()
        if digest!=item.get('sha256'): errors.append(f'hash mismatch: {item["path"]}')
        mode=stat.S_IMODE(p.stat().st_mode)
        if mode!=int(item['mode'],8): errors.append(f'mode mismatch: {item["path"]} expected={item["mode"]} actual={mode:04o}')
    return {'schema':REPORT_SCHEMA,'operation':'verify','ok':not errors,'checked':checked,'errors':errors,'target_binaries_copied':False}

def uninstall(manifest:dict[str,Any],dest_root:Path,purge_state:bool)->dict[str,Any]:
    dest_root=dest_root.resolve(); removed=[]; preserved=[]
    for item in manifest.get('files',[]):
        p=staged(dest_root,item['path'])
        if p.exists() or p.is_symlink(): p.unlink(); removed.append(item['path'])
    mp=staged(dest_root,manifest['manifest_path'])
    if mp.exists(): mp.unlink(); removed.append(manifest['manifest_path'])
    for d in sorted(manifest.get('directories',[]),key=lambda x:len(PurePosixPath(x['path']).parts),reverse=True):
        p=staged(dest_root,d['path']); kind=d.get('kind')
        if kind in {'state','target-input-root'} and not purge_state:
            preserved.append(d['path']); continue
        if purge_state and kind in {'state','target-input-root'}:
            if p.exists(): shutil.rmtree(p); removed.append(d['path'])
        else:
            try: p.rmdir(); removed.append(d['path'])
            except (FileNotFoundError,OSError): pass
    return {'schema':REPORT_SCHEMA,'operation':'uninstall','ok':True,'removed':removed,'preserved':preserved,'purge_state':purge_state}

def emit(doc:dict[str,Any],as_json:bool)->None:
    if as_json: print(json.dumps(doc,indent=2,sort_keys=True))
    else:
        print(f"{doc.get('operation','plan')}={'PASS' if doc.get('ok',True) else 'FAIL'}")
        for e in doc.get('errors',[]): print('ERROR: '+e,file=sys.stderr)

def add_plan_args(p:argparse.ArgumentParser)->None:
    p.add_argument('--root',type=Path,default=Path(__file__).resolve().parents[1])
    p.add_argument('--prefix',default='/opt/ppc-lab'); p.add_argument('--state-root',default='/var/lib/ppc-lab')
    p.add_argument('--config-root',default='/etc/ppc-lab'); p.add_argument('--cache-root',default='/var/cache/ppc-lab'); p.add_argument('--log-root',default='/var/log/ppc-lab')
    p.add_argument('--target-root',default='/srv/ppc-lab/targets'); p.add_argument('--run-user',default='ppclab')
    p.add_argument('--service',choices=['api','control','both'],default='both')
    p.add_argument('--api-host',default='127.0.0.1'); p.add_argument('--api-port',type=int,default=8765)
    p.add_argument('--job-timeout',type=int,default=60); p.add_argument('--max-body',type=int,default=1048576)
    p.add_argument('--control-max-active',type=int,default=2); p.add_argument('--control-poll-seconds',type=float,default=1.0)

def main()->int:
    ap=argparse.ArgumentParser(description=__doc__); sub=ap.add_subparsers(dest='cmd',required=True)
    p=sub.add_parser('plan'); add_plan_args(p); p.add_argument('--json',action='store_true')
    p=sub.add_parser('install'); add_plan_args(p); p.add_argument('--dest-root',type=Path,default=Path('/')); p.add_argument('--json',action='store_true')
    p=sub.add_parser('verify'); p.add_argument('manifest',type=Path); p.add_argument('--dest-root',type=Path,default=Path('/')); p.add_argument('--json',action='store_true')
    p=sub.add_parser('uninstall'); p.add_argument('manifest',type=Path); p.add_argument('--dest-root',type=Path,default=Path('/')); p.add_argument('--purge-state',action='store_true'); p.add_argument('--json',action='store_true')
    ns=ap.parse_args()
    try:
        if ns.cmd=='plan': emit(public_plan(build_plan(ns)),ns.json); return 0
        if ns.cmd=='install':
            report=install(build_plan(ns),ns.dest_root); emit(report,ns.json); return 0
        manifest=load_manifest(ns.manifest)
        if ns.cmd=='verify':
            report=verify(manifest,ns.dest_root); emit(report,ns.json); return 0 if report['ok'] else 1
        report=uninstall(manifest,ns.dest_root,ns.purge_state); emit(report,ns.json); return 0
    except (OSError,ValueError,json.JSONDecodeError,DeployError) as exc:
        print(f'ppc-lab-deploy: {exc}',file=sys.stderr); return 2
if __name__=='__main__': raise SystemExit(main())
